# Generated by Django 6.0.2 on 2026-02-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('enrollment_date', models.DateField()),
                ('city', models.CharField(default='Unknown', max_length=100)),  # ✅ Added correctly
            ],
        ),
    ]